FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_API_URL
ARG VITE_ENABLE_ADS
ARG VITE_ADSENSE_CLIENT_ID
ARG VITE_ADSENSE_SLOT_DASHBOARD_TOP
ARG VITE_ADSENSE_SLOT_DASHBOARD_BOTTOM
ARG VITE_ADSENSE_SLOT_INGRESOS_INLINE
ARG VITE_ADSENSE_SLOT_GASTOS_INLINE
ARG VITE_ADSENSE_SLOT_PRESUPUESTOS_INLINE
ARG VITE_ADSENSE_SLOT_RECORDATORIOS_INLINE
ARG VITE_ADSENSE_SLOT_CATEGORIAS_INLINE
ARG VITE_ADS_PLACEHOLDER_IN_DEV

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_ENABLE_ADS=$VITE_ENABLE_ADS
ENV VITE_ADSENSE_CLIENT_ID=$VITE_ADSENSE_CLIENT_ID
ENV VITE_ADSENSE_SLOT_DASHBOARD_TOP=$VITE_ADSENSE_SLOT_DASHBOARD_TOP
ENV VITE_ADSENSE_SLOT_DASHBOARD_BOTTOM=$VITE_ADSENSE_SLOT_DASHBOARD_BOTTOM
ENV VITE_ADSENSE_SLOT_INGRESOS_INLINE=$VITE_ADSENSE_SLOT_INGRESOS_INLINE
ENV VITE_ADSENSE_SLOT_GASTOS_INLINE=$VITE_ADSENSE_SLOT_GASTOS_INLINE
ENV VITE_ADSENSE_SLOT_PRESUPUESTOS_INLINE=$VITE_ADSENSE_SLOT_PRESUPUESTOS_INLINE
ENV VITE_ADSENSE_SLOT_RECORDATORIOS_INLINE=$VITE_ADSENSE_SLOT_RECORDATORIOS_INLINE
ENV VITE_ADSENSE_SLOT_CATEGORIAS_INLINE=$VITE_ADSENSE_SLOT_CATEGORIAS_INLINE
ENV VITE_ADS_PLACEHOLDER_IN_DEV=$VITE_ADS_PLACEHOLDER_IN_DEV

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
